/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_DATA_PB_H_INCLUDED
#define PB_DATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _SensorData {
    float sine_value;
    int32_t analog_value;
} SensorData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SensorData_init_default                  {0, 0}
#define SensorData_init_zero                     {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define SensorData_sine_value_tag                1
#define SensorData_analog_value_tag              2

/* Struct field encoding specification for nanopb */
#define SensorData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    sine_value,        1) \
X(a, STATIC,   SINGULAR, INT32,    analog_value,      2)
#define SensorData_CALLBACK NULL
#define SensorData_DEFAULT NULL

extern const pb_msgdesc_t SensorData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SensorData_fields &SensorData_msg

/* Maximum encoded size of messages (where known) */
#define DATA_PB_H_MAX_SIZE                       SensorData_size
#define SensorData_size                          16

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
